package com.example.stay.common.exception;

public enum ErrorCode {
    INVALID_SEARCH_CRITERIA,
    INVALID_CATALOG,
    INVALID_MAPPING,
    INVALID_INVENTORY,
    INVALID_MONEY,
    INVALID_OFFER,
    INVALID_SEARCH_RESULT,
    INVALID_SUPPLIER_FAILURE,
    INVALID_SUPPLIER_RESPONSE,
    INVALID_REQUEST,
    INTERNAL_ERROR
}
